services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://user:password@db:5432/database
    volumes:
      - .:/app
      - ./tmp/pids:/app/tmp/pids
      - ./log:/app/log

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: